=== hoangdat/tts-lowlevel/src/Text_DB.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" >


    <!-- definition of simple elements -->
    

    <!-- definition of attributes -->
    <xs:attribute name="type_phoneme" type="xs:string"/>
  


    <!-- definition of complex elements -->
    <xs:element name="syllable">
        <xs:complexType>
            <xs:attribute name = "id_syl" type="xs:integer"/>
            <xs:attribute name = "name" type="xs:string"/>
            <xs:attribute name = "start_index" type="xs:integer"/>
            <xs:attribute name = "end_index" type="xs:integer"/>
            <xs:attribute name = "position" type="xs:integer"/>
            <xs:attribute name = "num_of_phone" type="xs:integer"/>
            <xs:attribute name="energy" type="xs:float"/>
            <xs:sequence>
                <xs:element name = "initial" type ="xs:string">
                    <xs:complexType>
                        <xs:attribute ref="type_phoneme" />
                    </xs:complexType>
                </xs:element>
                <xs:element name = "middle" type ="xs:string">
                    <xs:complexType>
                        <xs:attribute ref="type_phoneme" use="required"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name = "nucleus" type ="xs:string">
                    <xs:complexType>
                        <xs:attribute ref="type_phoneme" use="required"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name = "final" type ="xs:string">
                    <xs:complexType>
                        <xs:attribute ref="type_phoneme" use="required"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name = "tone" type ="xs:integer"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <!--                -->
    <xs:element name="phrase">
        <xs:complexType>
            <xs:attribute name="id_phrase" type="xs:integer"/>
            <xs:attribute name="length" type="xs:integer"/>
            <xs:sequence>
                <xs:element ref="syllable"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <!--                           -->
    <xs:element name="sentence">
        <xs:complexType>
            <xs:attribute name="id_sen" type="xs:integer"/>
            <xs:sequence>
                <xs:element ref="phrase"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <!--                           -->
    <xs:element name="file" >
        <xs:complexType>
            <xs:attribute name="id_file" type="xs:integer"/>
            <xs:attribute name="file_name" type="xs:string" />
            <xs:sequence>
                <xs:element ref="sentence" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>


   
    <!--                  -->
    <xs:element name="category">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="file"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== hoangdat/tts-lowlevel/trunk/src/Text_DB_xsd.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : Text_DB_xsd.xml
    Created on : April 7, 2011, 11:42 PM
    Author     : thaodv_bkit
    Description:
        Purpose of the document follows.
-->

<ns1:category  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns:ns1='null'
   xsi:schemaLocation='null src/Text_DB.xsd'>
    <file id_file="" file_name="">
        <sentence id_sen="">
            <phrase id_phrase="" length="">
                <syllable id_syl="" name="" start_index="" end_index="" position="" num_of_phone="">
                    <initial></initial>
                    <middle></middle>
                    <nucleus></nucleus>
                    <final></final>
                    <tone></tone>
                </syllable>
            </phrase>
        </sentence>
    </file>

</ns1:category>
